spring.datasource.url=jdbc:mysql://localhost:3306/connecthub
spring.datasource.username=root
spring.datasource.password=Kingsiraj@24

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080